---
title: "ML-LR"
author: "Aqueel Premjee"
date: "6/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Importing libraries

```{r}
library(mlbench) # Contains several benchmark data sets (especially the Boston Housing dataset)
library(caret) # Package for machine learning algorithms / CARET stands for Classification  #                 and REgression Training
```

```{r}
# Importing the Boston Housing data set
data(BostonHousing)
```

```{r}
head(BostonHousing)
```


```{r}
# Check to see if there are missing data?
sum(is.na(BostonHousing))
```
```{r}
# To achieve reproducible model; set the random seed number
set.seed(64)
```

```{r}
# Performs stratified random split of the data set
TrainingIndex <- createDataPartition(BostonHousing$medv, p=0.8, list = FALSE)
TrainingSet <- BostonHousing[TrainingIndex,] # Training Set
TestingSet <- BostonHousing[-TrainingIndex,] # Test Set
```

```{r}
# Build Training model
Model <- train(medv ~ ., data = TrainingSet,
               method = "lm",
               na.action = na.omit,
               preProcess=c("scale","center"),
               trControl= trainControl(method="none")
)

```

```{r}
# Apply model for prediction
Model.training <-predict(Model, TrainingSet) # Apply model to make prediction on Training   #                                                 set
Model.testing <-predict(Model, TestingSet) # Apply model to make prediction on Testing set
```

```{r}
# Model performance (Displays scatter plot and performance metrics)
  # Scatter plot of Training set
    plot(TrainingSet$medv,Model.training, col = "blue" )
    plot(TestingSet$medv,Model.testing, col = "blue" )
```

```{r}
summary(model)
```


