---
title: "Plots in R"
author: "Aqueel Premjee"
date: "6/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(fmsb)
```



```{r}
# Create data: note in High school for several students
set.seed(99)
data <- as.data.frame(matrix( sample( 0:20 , 15 , replace=F) , ncol=5))

# Set the row and column names 
colnames(data) <- c("math" , "english" , "biology" , "music" , "R-coding" )
rownames(data) <- paste("mister" , letters[1:3] , sep="-")

# To use the fmsb package, add 2 lines to the dataframe: the max and min of each topic to show on the plot!
data <- rbind(rep(20,5) , rep(0,5) , data)

# Radar chart
colors_border <- c( rgb(0.2,0.5,0.5,0.9), rgb(0.8,0.2,0.5,0.9), rgb(0.7,0.5,0.1,0.9))
colors_in <- c( rgb(0.2,0.5,0.5,0.4), rgb(0.8,0.2,0.5,0.4), rgb(0.7,0.5,0.1,0.4))

radarchart(data, 
           axistype=1 , 
           #customize the polygons
           pcol=colors_border, 
           pfcol=colors_in, 
           plwd=4, 
           plty=1,
           #customize the grid
           cglcol="grey", 
           cglty=1, 
           axislabcol="grey", 
           caxislabels=seq(0,20,5), 
           cglwd=0.8,
           #custom labels
           vlcex=0.8)

# Add a legend
legend(x=0.7, y=1, legend=rownames(data[-c(1,2),]), bty="n", pch=20 , col=colors_in , text.col="grey", cex=1.2, pt.cex=3)
```
